### ISSUE TITLE
Avoid to pin dependency versions

### ISSUE THREAD

**Issue by c-bata** [uber/bayesmark#7]
> It is not considered best practice to use install_requires to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.
> https://packaging.python.org/discussions/install-requires-vs-requirements/

Currently, the versions of `install_requires` and `extra_requires` are pinned. But it's inconvenience for users. I propose that specifies what a project minimally needs to run correctly.

**Comment by rdturnermtl** [comment]
Currently, the `read_requirements` function in `setup.py` turns the `==` from the `.in` files into `>=`. So, I don't think `setup.py` is dictating any dependency with a `==`.

**Comment by c-bata** [comment]
I see. I close this. Thanks for your reply.
